version: '3'
services:
    ReverseProxy:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./webui/dist:/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: on-failure:3
        links:
            - DataBase
            - spring
    spring:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./spring/build/libs:/jar
        restart: on-failure:3
        links:
            - DataBase
    DataBase:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        restart: on-failure:3
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_USER: lain
            MYSQL_PASSWORD: mariadb
volumes:
    mysql: